# -*- coding: utf-8 -*-
"""15_1_part 3_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQevL5WglAVmyg4ia-WHWtb9ToIlfkE6
"""

import flask
from flask import request, jsonify
import joblib
import numpy as np


model = joblib.load('/content/model.pkl')

app = flask.Flask(__name__)


@app.route('/predict', methods=['POST'])
def predict():
    try:

        data = request.get_json()
        input_data = np.array(data['input']).reshape(1, -1)
        prediction = model.predict(input_data)
        return jsonify({'prediction': prediction.tolist()})

    except Exception as e:
        return jsonify({'error': str(e)})


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)