# -*- coding: utf-8 -*-
"""15_1_part 3_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIIhDt6Ml1L5tBHlc8rPT-bL5_VnErLX
"""

from flask import Flask, request, jsonify
import pickle


with open('heart_disease_diagnosis_model.pkl', 'rb') as f:
    model = pickle.load(f)

app = Flask(name)

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    input_data = data['features']
    prediction = int(model.predict([input_data])[0])
    return jsonify({'prediction': prediction})


if name == 'main':
    app.run(host='0.0.0.0', port=5000)